apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ridetrack.fullname" . }}-secret
  labels:
    {{- include "ridetrack.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGODB_URI: {{ .Values.secrets.mongodbUri | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  RABBITMQ_URL: {{ .Values.secrets.rabbitmqUrl | quote }}
  REDIS_URL: {{ .Values.secrets.redisUrl | quote }}
